# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(376, 237)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(6, 10, 171, 16))
        self.label_20.setObjectName("label_20")
        self.gaopin = QtWidgets.QLineEdit(Form)
        self.gaopin.setGeometry(QtCore.QRect(190, 10, 141, 21))
        self.gaopin.setText("")
        self.gaopin.setPlaceholderText("")
        self.gaopin.setObjectName("gaopin")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(6, 40, 171, 16))
        self.label_21.setObjectName("label_21")
        self.dipin = QtWidgets.QLineEdit(Form)
        self.dipin.setGeometry(QtCore.QRect(190, 40, 141, 21))
        self.dipin.setText("")
        self.dipin.setPlaceholderText("")
        self.dipin.setObjectName("dipin")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(6, 70, 171, 16))
        self.label_22.setObjectName("label_22")
        self.lama_export = QtWidgets.QLineEdit(Form)
        self.lama_export.setGeometry(QtCore.QRect(190, 70, 141, 21))
        self.lama_export.setText("")
        self.lama_export.setPlaceholderText("")
        self.lama_export.setObjectName("lama_export")
        self.lama_import = QtWidgets.QLineEdit(Form)
        self.lama_import.setGeometry(QtCore.QRect(190, 100, 141, 21))
        self.lama_import.setText("")
        self.lama_import.setPlaceholderText("")
        self.lama_import.setObjectName("lama_import")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(6, 100, 171, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(6, 130, 171, 16))
        self.label_24.setObjectName("label_24")
        self.yingdiao = QtWidgets.QLineEdit(Form)
        self.yingdiao.setGeometry(QtCore.QRect(190, 130, 141, 21))
        self.yingdiao.setText("")
        self.yingdiao.setPlaceholderText("")
        self.yingdiao.setObjectName("yingdiao")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(6, 160, 171, 16))
        self.label_25.setObjectName("label_25")
        self.baohe = QtWidgets.QLineEdit(Form)
        self.baohe.setGeometry(QtCore.QRect(190, 160, 141, 21))
        self.baohe.setText("")
        self.baohe.setPlaceholderText("")
        self.baohe.setObjectName("baohe")
        self.check_btn = QtWidgets.QPushButton(Form)
        self.check_btn.setGeometry(QtCore.QRect(140, 200, 91, 23))
        self.check_btn.setObjectName("check_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p align=\"center\">创建高频层快捷键</p></body></html>"))
        self.gaopin.setToolTip(_translate("Form", "不需要多任务流水线的话，自动对ps当前的文档进行执行，可以不用填写。如需一图多修，可将其他任务的文档名改成与这个图片一致的文档名。"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p align=\"center\">创建低频层快捷键</p></body></html>"))
        self.dipin.setToolTip(_translate("Form", "不需要多任务流水线的话，自动对ps当前的文档进行执行，可以不用填写。如需一图多修，可将其他任务的文档名改成与这个图片一致的文档名。"))
        self.label_22.setText(_translate("Form", "<html><head/><body><p align=\"center\">Lama导入快捷键</p></body></html>"))
        self.lama_export.setToolTip(_translate("Form", "不需要多任务流水线的话，自动对ps当前的文档进行执行，可以不用填写。如需一图多修，可将其他任务的文档名改成与这个图片一致的文档名。"))
        self.lama_import.setToolTip(_translate("Form", "不需要多任务流水线的话，自动对ps当前的文档进行执行，可以不用填写。如需一图多修，可将其他任务的文档名改成与这个图片一致的文档名。"))
        self.label_23.setText(_translate("Form", "<html><head/><body><p align=\"center\">Lama传回快捷键</p></body></html>"))
        self.label_24.setText(_translate("Form", "<html><head/><body><p align=\"center\">影调观察层快捷键</p></body></html>"))
        self.yingdiao.setToolTip(_translate("Form", "不需要多任务流水线的话，自动对ps当前的文档进行执行，可以不用填写。如需一图多修，可将其他任务的文档名改成与这个图片一致的文档名。"))
        self.label_25.setText(_translate("Form", "<html><head/><body><p align=\"center\">饱和观察层快捷键</p></body></html>"))
        self.baohe.setToolTip(_translate("Form", "不需要多任务流水线的话，自动对ps当前的文档进行执行，可以不用填写。如需一图多修，可将其他任务的文档名改成与这个图片一致的文档名。"))
        self.check_btn.setText(_translate("Form", "确认"))
